
development:
  adapter: postgresql
  encoding: unicode
  database: bird_tracker_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bird_tracker_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bird_tracker_production
  pool: 5
  username:
  password:
